"use client";
import React, { useEffect, useState } from "react";
import { Avatar, Card } from "antd";
import { FaUser, FaEdit, FaMoneyCheckAlt } from "react-icons/fa";
import { Routes, Route, useParams, useNavigate } from "react-router-dom";
import userApi from "../../api/userApi";
import Account from "../../components/account";
import Address from "../../components/address";
import ChangePassword from "../../components/change-password";
import OrderDetail from "../../components/orderDetail";
